////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#ifndef [=$module]_STDAFX_H_INCLUDED
#define [=$module]_STDAFX_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

[if $mfc]
#define VC_EXTRALEAN // Exclude rarely-used stuff from Windows headers
#include <afx.h>
#include <afxwin.h>
#include <afxdisp.h>
#include <atlconv.h>
[else]
#include <tchar.h>
[endif]

#include <comdef.h>

#pragma warning ( disable : 4786 )	// identifier was truncated to '255' characters in the debug information
#pragma warning ( disable : 4800 )	// forcing value to bool 'true' or 'false' (performance warning)

#include <set>
#include <map>
#include <list>
#include <vector>
#include <string>
#include <iosfwd>
#include <fstream>
#include <sstream>
#include <iostream>
#include <functional>
#include <algorithm>
using namespace std;

namespace altova {};
using namespace altova;

#include "../Altova/Altova.h"
#include "../Altova/AltovaException.h"
#include "../Altova/SchemaTypes.h"
#include "../Altova/SchemaTypeString.h"
#include "../Altova/SchemaTypeNumber.h"
#include "../Altova/SchemaTypeCalendar.h"
#include "../Altova/SchemaTypeBinary.h"

#include "../AltovaText/TextException.h"
#include "../AltovaText/TextDocument.h"
#include "../AltovaText/TextNode.h"
#include "../AltovaText/Function.h"


//{{AFX_INSERT_LOCATION}}

#endif // [=$module]_STDAFX_H_INCLUDED
