/**
 * SchemaToken.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaToken extends SchemaNormalizedString {
	public SchemaToken() {
		super();
	}

	public SchemaToken(String newvalue) {
		super(newvalue);
	}

	public SchemaToken(SchemaToken newvalue) {
		super((SchemaNormalizedString)newvalue);
	}
}
