/**
 * SchemaNMToken.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaNMToken extends SchemaToken {
	public SchemaNMToken() {
		super();
	}

	public SchemaNMToken(String newvalue) {
		super(newvalue);
	}

	public SchemaNMToken(SchemaNMToken newvalue) {
		super((SchemaToken)newvalue);
	}
}
