/**
 * SchemaTypeBinary.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public interface SchemaTypeBinary extends SchemaType {
  // constants for declaration of types which have an date/time/duration value
  public final int BINARY_VALUE_UNDEFINED = -1; // string may contain every type of binary value

  public final int BINARY_VALUE_BASE64 = 0;
  public final int BINARY_VALUE_HEX = 1;

  public int binaryType();
}
