/**
 * SchemaLanguage.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaLanguage extends SchemaToken {
	public SchemaLanguage() {
		super();
	}

	public SchemaLanguage(String newvalue) {
		super(newvalue);
	}

	public SchemaLanguage(SchemaLanguage newvalue) {
		super((SchemaToken)newvalue);
	}
}
