/**
 * StringParseException.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.types;


public class StringParseException extends SchemaTypeException {
  int position;

  public StringParseException(String text, int newposition) {
    super(text);
    position = newposition;
  }

  public StringParseException(Exception other) {
    super(other);
  }
}
