//
// [=$module]Doc.cs
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//


using System;

namespace [=$moduleName]
{
	public class [=$moduleName]Doc : Altova.Xml.Document
	{
		override protected void DeclareNamespaces(Altova.Xml.Node node)
		{
[foreach $namespace in $namespaces
	if $namespace.URI <> ""
]			DeclareNamespace(node, "[=$namespace.Prefix]", "[=$namespace.URI]");
[	endif
next
]		}
	}
}
