////////////////////////////////////////////////////////////////////////
//
// [=$module].cpp
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#include "StdAfx.h"
#include "[=$module].h"
[if $library.IsTree]
#include "[=$module]Functions.h"
#include "../AltovaText/Generator.h"
[if $library.ParseMode = 0 ' EDI
]#include "../AltovaText/Functions.h"
#include "../AltovaText/Helpers.h"
[else]
#include "../AltovaText/FlexCommand.h"
using namespace altova::text::flex;
[endif ' EDI
]
using namespace altova;
using namespace altova::text;
[endif ' IsTree

if $library.ParseMode = 1]
#include "../AltovaText/CSVSerializer.h"
[endif]
[if $library.ParseMode = 2]
#include "../AltovaText/FLFSerializer.h"
[endif]

namespace [=$module]
{
[
	if $library.ParseMode = 0
		include "cpp/LibraryText/LibraryTextEDI.cpp"
	endif
	if $library.ParseMode = 1
		include "cpp/LibraryText/LibraryTextCSV.cpp"
	endif
	if $library.ParseMode = 2
		include "cpp/LibraryText/LibraryTextFLF.cpp"
	endif
	if $library.ParseMode = 3
		include "cpp/LibraryText/LibraryTextTXT.cpp"
	endif
]
}//namespace [=$module]
