////////////////////////////////////////////////////////////////////////
//
// [=$module]API.h
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#ifndef [=$module]API_H_INCLUDED
#define [=$module]API_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#ifndef _USRDLL
	#define [=$module]_DECLSPECIFIER
#else
	#ifdef [=$module]_EXPORTS
		#define [=$module]_DECLSPECIFIER __declspec(dllexport)
	#else
		#define [=$module]_DECLSPECIFIER __declspec(dllimport)
	#endif
#endif

#endif // [=$module]API_H_INCLUDED
