/**
 * [=$application.Name]WebService.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package [=$JavaPackageName];

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import java.rmi.RemoteException;

import com.altova.types.*;
[foreach $library in $application.Libraries
	if $library.Kind = 5
]import [=$JavaPackageName].[=$library.Name].*;
[	endif
next]

public class [=$application.WSDLService.Name]WebService {

	// WebService method
	boolean isFault=false;
	
[foreach $mapping in $application.Mappings]
	public Element\[\] [=$mapping.WSDLBindingOperation.Name] (Element\[\] requestElements) throws java.rmi.RemoteException
	{
		[$lInstance = "requestElements"]
		org.w3c.dom.Node responseNode=null;
		try {
			TraceTargetConsole ttc = new TraceTargetConsole();

[			$AlgorithmGroups = $mapping.AlgorithmGroups
			include "java/mapforce/ApplicationMain.java"
]		} 
		catch (org.apache.axis.AxisFault af) {
			throw af;
		}
		catch (Exception e) {
			throw new RemoteException(e.getMessage(), e);
		}
	}
[next]
}

class TraceTargetConsole implements com.altova.TraceTarget {
	public void writeTrace(String info) {
		System.out.println(info);
	}
}
