/**
 * TraceProvider.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova;


public abstract class TraceProvider {
	protected TraceTarget traceTarget = null;

	protected void writeTrace(String info) {
		if (traceTarget != null)
			traceTarget.writeTrace(info);
	}

	public void registerTraceTarget(TraceTarget newTraceTarget) {
		traceTarget = newTraceTarget;
	}

	public void unregisterTraceTarget() {
		traceTarget = null;
	}
}
