//
// Command.cs
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//

using System;
using System.Collections;
using System.Data;
using Altova.Types;

namespace Altova.Db
{

	public class Command 
	{
		// members
		protected string	statement	 = "";
		protected ArrayList	parameters   = new ArrayList();
		protected bool		isAutoReadFieldsIntoBuffer = false;

		// construction
		public Command(string statement, bool isAutoReadFieldsIntoBuffer)
		{
			this.statement = statement;
			this.isAutoReadFieldsIntoBuffer = isAutoReadFieldsIntoBuffer;
		}

		// accessors
		public string Statement
		{
			get
			{
				return statement;
			}

			set
			{
				statement = value;
			}
		}

		public ArrayList Parameters
		{
			get
			{
				return parameters;
			}
		}

		public bool IsAutoReadFieldsIntoBuffer
		{
			get
			{
				return isAutoReadFieldsIntoBuffer;
			}
			
			set
			{
				isAutoReadFieldsIntoBuffer = value;
			}
		}

		// methods
		public bool IsEmpty()
		{
			return statement == "";
		}

		public void AddParameter(ISchemaType val, bool isAutoUpdate)
		{
			parameters.Add( new FieldValue( "P" + Convert.ToString( parameters.Count ), val, isAutoUpdate ) );
		}
	}
}