//
// FieldValue.cs
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//

using System;
using Altova.Types;

namespace Altova.Db
{

	public class FieldValue 
	{
		public string		Name = "";
		public ISchemaType	Value = null;
		public bool			IsAutoUpdate = false;

		public FieldValue(string name, ISchemaType value, bool isAutoUpdate)
		{
			this.Name = name;
			this.Value = value;
			this.IsAutoUpdate = isAutoUpdate;
		}
	}
}