////////////////////////////////////////////////////////////////////////
//
// Db.cpp
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#include "StdAfx.h"
#include <Altova.h>
#include <SchemaTypes.h>
#include <AltovaException.h>
#include <SchemaTypeCalendar.h>
#include <SchemaTypeNumber.h>
#include <SchemaTypeString.h>
#include <SchemaTypeBinary.h>
#include "Db.h"

namespace altova {


//TMapLongToLong	Lang::ms_AutoNumberValues;	// not used at the moment


CSchemaString	Db::SetNull()
{
	CSchemaString sRes;
	sRes.SetIsNull( true );
	return sRes;
}


} // namespace altova
