////////////////////////////////////////////////////////////////////////
//
// Db.h
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#ifndef ALTOVAFUNCTIONS_DB_H_INCLUDED
#define ALTOVAFUNCTIONS_DB_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include "Core.h"	// template definitions and utility-functions


namespace altova {

class ALTOVAFUNCTIONS_DECLSPECIFIER Db
{
public:
	Db() {};

////////////////////////////////////////////////////////////////////////
//
//  Null processing functions
//
////////////////////////////////////////////////////////////////////////

	static CSchemaString	SetNull();


////////////////////////////////////////////////////////////////////////
//
//  Members
//
////////////////////////////////////////////////////////////////////////
protected:
//	static TMapLongToLong	ms_AutoNumberValues;	// not used at the moment
};

} // namespace altova

#endif // ALTOVAFUNCTIONS_DB_H_INCLUDED
