////////////////////////////////////////////////////////////////////////
//
// Edifact.h
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////

#ifndef ALTOVAFUNCTIONS_EDIFACT_H_INCLUDED
#define ALTOVAFUNCTIONS_EDIFACT_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000

#include "Core.h"	// template definitions and utility-functions

namespace altova {

class ALTOVAFUNCTIONS_DECLSPECIFIER Edifact
{
	Edifact()  {};
	~Edifact() {};
public:

////////////////////////////////////////////////////////////////////////
//
//  Datetime functions
//
////////////////////////////////////////////////////////////////////////

	static CSchemaDate		ToDate(const CSchemaString& rValue, const CSchemaString& rFormat);
	static CSchemaTime		ToTime(const CSchemaString& rValue, const CSchemaString& rFormat);
	static CSchemaDateTime	ToDatetime(const CSchemaString& rValue, const CSchemaString& rFormat);
	static CSchemaDuration	ToDuration(const CSchemaString& rValue, const CSchemaString& rFormat);
	static CSchemaString	Autoformat(const CSchemaString& rValue, const CSchemaString& rFormat);

};// class Edifact

} // namespace altova

#endif // ALTOVAFUNCTIONS_EDIFACT_H_INCLUDED
