////////////////////////////////////////////////////////////////////////
//
// StdAfx.h
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//
////////////////////////////////////////////////////////////////////////


#ifndef ALTOVA_STDAFX_H_INCLUDED
#define ALTOVA_STDAFX_H_INCLUDED

#if _MSC_VER > 1000
	#pragma once
#endif // _MSC_VER > 1000


[if $mfc]
#define VC_EXTRALEAN // Exclude rarely-used stuff from Windows headers
#include <afx.h>
#include <afxwin.h>
#include <afxdisp.h>
[else]
#include <tchar.h>
[endif]


[if $DBLibraryCount > 0]
#pragma warning(disable: 4146)
// If you get a compiler-error on the line below, add the path to the DLL
// at Tools|Options|Directories|Include Directories.
// Hint: Depending on your installation it might be C:\\Program Files\\Common Files\\System\\ADO
#import "msado15.dll" rename("EOF", "EndOfFile") no_implementation
#pragma warning(default: 4146)
[endif]

#pragma warning( disable: 4786 )

#include <iostream>
#include <string>
#include <map>


//{{AFX_INSERT_LOCATION}}

#endif // ALTOVA_STDAFX_H_INCLUDED
