/**
 * Command.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.db;

import com.altova.types.*;
import java.util.Vector;


public class Command {
	// members
	protected String	statement;
	protected Vector	parameters;
	protected boolean	isAutoReadFieldsIntoBuffer;

	// construction
	public Command(String newStatement, boolean newIsAutoReadFieldsIntoBuffer) {
		statement = newStatement;
		isAutoReadFieldsIntoBuffer = newIsAutoReadFieldsIntoBuffer;
		parameters = new Vector();
	}

	// accessors
	public String getStatement() {
		return statement;
	}

	public void setStatement(String newValue) {
		statement = newValue;
	}

	public Vector getParameters() {
		return parameters;
	}

	public boolean isAutoReadFieldsIntoBuffer()	{
		return isAutoReadFieldsIntoBuffer;
	}

	public void setAutoReadFieldsIntoBuffer(boolean newValue) {
		isAutoReadFieldsIntoBuffer = newValue;
	}

	// methods
	public boolean isEmpty() {
		return statement.length() == 0;
	}

	public void addParameter(SchemaType newValue, boolean isAutoUpdate)	{
		parameters.addElement( new FieldValue( "P" + Integer.toString( parameters.size() ), newValue, isAutoUpdate ) );
	}
}
