/**
 * DbConnectionException.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.db;


public class DbConnectionException extends DbException {
	// error kind enum
	public static final int	OPEN = 0;
	public static final int	INIT = 1;
	public static final int	FINALIZE = 2;
	public static final int	CLOSE = 3;

	protected int		nErrorKind;

	// construction
	public DbConnectionException( int errorKind, String connectionString, String errorMessage ) {
		super( connectionString, errorMessage );
		nErrorKind = errorKind;
	}

	public DbConnectionException(Exception other) {
		super(other);
	}

	// accessors
	public int getKind() {
		return nErrorKind;
	}

	public String getConnectionString() {
		return sFailedItem;
	}
}
