//
// [=$module].cs
//
// This file was generated by [=$Host].
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the [=$HostShort] Documentation for further details.
// [=$HostURL]
//

using System;
using System.Collections;
using Altova;
using Altova.Types;
using Altova.TextParser;

namespace [=$module]
{
[	if $library.ParseMode = 0]
using Altova.TextParser.EDIFACT;
[		include "cs/LibraryText/LibraryTextEDI.spl"
	endif

	if $library.ParseMode = 1]
using Altova.TextParser.TableLike;
using Altova.TextParser.TableLike.CSV;
[		include "cs/LibraryText/LibraryTextCSV.spl"
	endif

	if $library.ParseMode = 2]
using Altova.TextParser.TableLike;
using Altova.TextParser.TableLike.FLF;
[		include "cs/LibraryText/LibraryTextFLF.spl"
	endif

	if $library.ParseMode = 3]
using Altova.TextParser.Flex;
[		include "cs/LibraryText/LibraryTextTXT.spl"
	endif
]
} // namespace [=$module]
