/**
 * SchemaEntity.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaEntity extends SchemaNCName {
	public SchemaEntity() {
		super();
	}

	public SchemaEntity(String newvalue) {
		super(newvalue);
	}

	public SchemaEntity(SchemaEntity newvalue) {
		super((SchemaNCName)newvalue);
	}
}
