/**
 * SchemaID.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaID extends SchemaNCName {
	public SchemaID() {
		super();
	}

	public SchemaID(String newvalue) {
		super(newvalue);
	}

	public SchemaID(SchemaID newvalue) {
		super((SchemaNCName)newvalue);
	}
}
