/**
 * SchemaNCName.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaNCName extends SchemaName {
	public SchemaNCName() {
		super();
	}

	public SchemaNCName(String newvalue) {
		super(newvalue);
	}

	public SchemaNCName(SchemaNCName newvalue) {
		super((SchemaName)newvalue);
	}
}
