/**
 * SchemaName.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaName extends SchemaToken {
	public SchemaName() {
		super();
	}

	public SchemaName(String newvalue) {
		super(newvalue);
	}

	public SchemaName(SchemaName newvalue) {
		super((SchemaToken)newvalue);
	}
}
