/**
 * SchemaNormalizedString.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */

package com.altova.types;

public class SchemaNormalizedString extends SchemaString {
	public SchemaNormalizedString() {
		super();
	}

	public SchemaNormalizedString(String newvalue) {
		super(newvalue);
	}

	public SchemaNormalizedString(SchemaNormalizedString newvalue) {
		super((SchemaString)newvalue);
	}
}
