/**
 * DbException.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.db;


public class DbException extends com.altova.AltovaException {
	protected String sFailedItem;
	protected String sErrorMessage;

	// construction
	public DbException( String failedItem, String errorMessage ) {
		super( failedItem + " \\n" + errorMessage );
		sFailedItem = failedItem;
		sErrorMessage = errorMessage;
	}

	public DbException(Exception other) {
		super(other);
	}

	// accessors
	public String getFailedItem() {
		return sFailedItem;
	}

	public String getErrorMessage() {
		return sErrorMessage;
	}
}
