/**
 * DbTransactionException.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.db;


public class DbTransactionException extends DbException {
	// action-kind enumeration
	public static final int	ROLLBACK_ALL = 0;
	public static final int	STOP = 1;

	protected int					nActionKind;
	protected DbExecuteException	oInnerExecuteException;

	// construction
	public DbTransactionException( int actionKind, String transactionName, DbExecuteException e ) {
		super( transactionName, e.getErrorMessage() );
		nActionKind = actionKind;
		oInnerExecuteException = e;
	}

	public DbTransactionException(Exception other) {
		super(other);
	}

	// accessors
	public int getActionKind() {
		return nActionKind;
	}

	public String getTransactionName() {
		return sFailedItem;
	}

	public DbExecuteException	getInnerDbExecuteException() {
		return oInnerExecuteException;
	}
}
