/**
 * FieldValue.java
 *
 * This file was generated by [=$Host].
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the [=$HostShort] Documentation for further details.
 * [=$HostURL]
 */


package com.altova.db;

import com.altova.types.*;


public class FieldValue {
	public String		name = "";
	public SchemaType	value = null;
	public boolean		isAutoUpdate = false;

	public FieldValue(String newname, SchemaType newvalue, boolean newIsAutoUpdate)
	{
		name = newname;
		value = newvalue;
		isAutoUpdate = newIsAutoUpdate;
	}
}
